spool create_tbls.log

set echo on
set timing on

CREATE BIGFILE TABLESPACE AUDITORIA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 85G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE AUDITORIA_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 2G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE AUDITORIA_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 5G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE AVERBACAO NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 60G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE CONCILIACAO_DB NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 4500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE CONTRATO NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 16G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE LOGS NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 18G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE SALDO_CONTRATOS NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 50G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE TABELAS_PART NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 82G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE TABELAS_SSD NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 70G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE TBSP_AUDITORIA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 13G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE TBS_MOVE_01 NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 1G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE PARCELAS NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 350G AUTOEXTEND ON NEXT 1G;
CREATE BIGFILE TABLESPACE INDICES NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 1600G AUTOEXTEND ON NEXT 1G;
CREATE BIGFILE TABLESPACE SCCTOOLSD NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 4000G AUTOEXTEND ON NEXT 1G;

spool off