spool roles.log
set echo on
CREATE ROLE CONCILIACAO;
CREATE ROLE CONNECT_10G;
CREATE ROLE DBA_PROD;
CREATE ROLE DBA_SELECT;
CREATE ROLE RL_SCCTOOLS_SELECT;
CREATE ROLE RL_SUPORTERJ_SELECT;
CREATE ROLE RL_SUPORTE_TI;
CREATE ROLE RL_SUPORTE_TI_DML;
CREATE ROLE RL_SUPORTE_TI_EXEC;
CREATE ROLE RL_TOOLS_SELECT;
CREATE ROLE TC_ADMIN_ROLE;
CREATE ROLE TC_LDR_ROLE;
CREATE ROLE TC_MGR_ROLE;
CREATE ROLE TEMP_VIEWS_SELECT;
spool off