spool human_USER_DATA.log
set echo on feedback on timing on

CREATE USER "DIEGO_CABRAL" IDENTIFIED BY VALUES 'C88CC1F142039A57' DEFAULT TABLESPACE "SCCTOOLSD" TEMPORARY TABLESPACE "TEMP01" PROFILE "USUARIOS";
CREATE USER "FELIPE_MENEZES" IDENTIFIED BY VALUES 'DE5D63622265F423' DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP01" PROFILE "USUARIOS";
CREATE USER "IAN_CARVALHO" IDENTIFIED BY VALUES '2F600E3EEDD44C62' DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP01";
CREATE USER "JOAO_ALVES" IDENTIFIED BY VALUES '8CA6391C6AF46926' DEFAULT TABLESPACE "USERS" TEMPORARY TABLESPACE "TEMP01";
CREATE USER "PIERRE_RIBEIRO" IDENTIFIED BY VALUES 'EE2EBD40697498B8' TEMPORARY TABLESPACE "TEMP01";
CREATE USER "MARCELOF_TOOLS" IDENTIFIED BY VALUES '3B0BDC0F601DB641' DEFAULT TABLESPACE "SCCTOOLSD" TEMPORARY TABLESPACE "TEMP01" PROFILE "USUARIOS";



ALTER USER "DIEGO_CABRAL" DEFAULT ROLE ALL;
ALTER USER "FELIPE_MENEZES" DEFAULT ROLE ALL;
ALTER USER "JOAO_ALVES" DEFAULT ROLE ALL;
ALTER USER "PIERRE_RIBEIRO" DEFAULT ROLE ALL;
ALTER USER "MARCELOF_TOOLS" DEFAULT ROLE ALL;
ALTER USER "IAN_CARVALHO" DEFAULT ROLE ALL;

spool off