CREATE TABLE "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" 
   (	
    "ROTINA" VARCHAR2(30) NOT NULL ENABLE, 
	"DATA" DATE NOT NULL ENABLE, 
	"HORA" VARCHAR2(8) NOT NULL ENABLE, 
	"QTD_REGISTROS" NUMBER NOT NULL ENABLE, 
	"MSG" VARCHAR2(255)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  FREELISTS 15 BUFFER_POOL DEFAULT)
  TABLESPACE "SCCTOOLSD";
 
  ALTER TABLE "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" MODIFY ("ROTINA" NOT NULL ENABLE);
 
  ALTER TABLE "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" MODIFY ("DATA" NOT NULL ENABLE);
 
  ALTER TABLE "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" MODIFY ("HORA" NOT NULL ENABLE);
 
  ALTER TABLE "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" MODIFY ("QTD_REGISTROS" NOT NULL ENABLE);
 
  GRANT DELETE ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "SCCTOOLS_JOBS";
 
  GRANT INSERT ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "SCCTOOLS_JOBS";
 
  GRANT SELECT ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "SCCTOOLS_JOBS";
 
  GRANT UPDATE ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "SCCTOOLS_JOBS";
 
  GRANT SELECT ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "RL_SUPORTE_TI";
 
  GRANT DELETE ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "RL_SUPORTE_TI_DML";
 
  GRANT INSERT ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "RL_SUPORTE_TI_DML";
 
  GRANT UPDATE ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "RL_SUPORTE_TI_DML";
 
  GRANT SELECT ON "SCCTOOLS"."TMP_LOG_PROCESSAMENTO" TO "LK_TOOLS_BACEN";