CREATE TABLE "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" 
   (	"USUARIO" VARCHAR2(150) NOT NULL ENABLE, 
	"DT_OCOR" DATE DEFAULT SYSDATE, 
	"TELA" VARCHAR2(500), 
	"PROC_ORACLE" VARCHAR2(500)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(
  BUFFER_POOL DEFAULT)
  TABLESPACE "LOGS" 
  PARTITION BY RANGE ("DT_OCOR") 
 (
 
 PARTITION "partition_2011"  VALUES LESS THAN (TO_DATE(' 2012-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255  NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LOGS" NOCOMPRESS ,  
 PARTITION "partition_2012"  VALUES LESS THAN (TO_DATE(' 2013-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 8388608 NEXT 8388608 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LOGS" NOCOMPRESS ,
 PARTITION "partition_2013"  VALUES LESS THAN (TO_DATE(' 2014-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 8388608 NEXT 8388608 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LOGS" NOCOMPRESS ,  
 PARTITION "OUTROS"  VALUES LESS THAN (MAXVALUE) 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
  STORAGE(INITIAL 8388608 NEXT 8388608 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "LOGS" NOCOMPRESS ) ;
 
  ALTER TABLE "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" MODIFY ("USUARIO" NOT NULL ENABLE);
 
  GRANT DELETE ON "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" TO "SUPORTERJ_JOBS";
 
  GRANT INSERT ON "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" TO "SUPORTERJ_JOBS";
 
  GRANT SELECT ON "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" TO "SUPORTERJ_JOBS";
 
  GRANT UPDATE ON "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" TO "SUPORTERJ_JOBS";
 
  GRANT SELECT ON "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" TO "RL_SUPORTE_TI";
 
  GRANT DELETE ON "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" TO "RL_SUPORTE_TI_DML";
 
  GRANT INSERT ON "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" TO "RL_SUPORTE_TI_DML";
 
  GRANT UPDATE ON "SUPORTERJ"."BCSUL_T_LOG_APOIO_PRODUCAO" TO "RL_SUPORTE_TI_DML";