GRANT "CONNECT" TO "ATENDIMENTO"; 
GRANT "RESOURCE" TO "ATENDIMENTO";
GRANT "CONNECT_10G" TO "ATENDIMENTO";
GRANT "QUEST_SL_SQLAB_ROLE" TO "ATENDIMENTO";
GRANT SELECT ANY TABLE TO "ATENDIMENTO";
GRANT UNLIMITED TABLESPACE TO "ATENDIMENTO";

GRANT "CONNECT" TO "AVERB";
GRANT "RESOURCE" TO "AVERB";
GRANT "CONNECT_10G" TO "AVERB";
GRANT "TEMP_VIEWS_SELECT" TO "AVERB";
GRANT "QUEST_SL_SQLAB_ROLE" TO "AVERB";
GRANT "PLUSTRACE" TO "AVERB";
GRANT CREATE JOB TO "AVERB";
GRANT DEBUG ANY PROCEDURE TO "AVERB";
GRANT DEBUG CONNECT SESSION TO "AVERB";
GRANT CREATE VIEW TO "AVERB";
GRANT UNLIMITED TABLESPACE TO "AVERB";
GRANT ALTER SESSION TO "AVERB";

GRANT "CONNECT" TO "AVERB_JOBS";
GRANT "RESOURCE" TO "AVERB_JOBS";
GRANT "CONNECT_10G" TO "AVERB_JOBS";
GRANT "TEMP_VIEWS_SELECT" TO "AVERB_JOBS";
GRANT "QUEST_SL_SQLAB_ROLE" TO "AVERB_JOBS";
GRANT CREATE JOB TO "AVERB_JOBS";
GRANT DEBUG CONNECT SESSION TO "AVERB_JOBS";
GRANT ALTER ANY MATERIALIZED VIEW TO "AVERB_JOBS";
GRANT CREATE ANY MATERIALIZED VIEW TO "AVERB_JOBS";
GRANT CREATE DATABASE LINK TO "AVERB_JOBS";
GRANT CREATE VIEW TO "AVERB_JOBS";
GRANT SELECT ANY TABLE TO "AVERB_JOBS";
GRANT UNLIMITED TABLESPACE TO "AVERB_JOBS";
GRANT ALTER SESSION TO "AVERB_JOBS";

GRANT "CONNECT" TO "BCSUL";
GRANT "CONNECT_10G" TO "BCSUL";
GRANT "QUEST_SL_SQLAB_ROLE" TO "BCSUL";


GRANT "CONNECT" TO "BDD";
GRANT "RESOURCE" TO "BDD";
GRANT UNLIMITED TABLESPACE TO "BDD";
GRANT SELECT ON "SUPORTERJ"."BSI_V_BOLETO_BDD" TO "BDD";
GRANT EXECUTE ON "SUPORTERJ"."SP_RCB_BAIXA_BDD" TO "BDD";


GRANT "CONNECT" TO "BDD_HOMOLOG";
GRANT "RESOURCE" TO "BDD_HOMOLOG";
GRANT UNLIMITED TABLESPACE TO "BDD_HOMOLOG";
GRANT EXECUTE ON "SCQ_HOMOLOG"."SP_RCB_BAIXA_BDD" TO "BDD_HOMOLOG";
GRANT SELECT ON "SCQ_HOMOLOG"."BSI_V_BOLETO_BDD" TO "BDD_HOMOLOG";


GRANT "CONNECT" TO "CI";
GRANT "RESOURCE" TO "CI";
GRANT "RL_SUPORTE_TI" TO "CI";
GRANT CREATE MATERIALIZED VIEW TO "CI";
GRANT SELECT ANY TABLE TO "CI";
GRANT UNLIMITED TABLESPACE TO "CI";


GRANT "CONNECT" TO "CONCILIACAO_DB";
GRANT "RESOURCE" TO "CONCILIACAO_DB";
GRANT "RL_SUPORTE_TI" TO "CONCILIACAO_DB";
GRANT SELECT ANY TABLE TO "CONCILIACAO_DB";
GRANT UNLIMITED TABLESPACE TO "CONCILIACAO_DB";


GRANT "CONNECT" TO "DBL_BI_ODI";
GRANT SELECT ON "AVERB"."AVC_A16_SUBDIVISOES" TO "DBL_BI_ODI";
GRANT SELECT ON "SCCTOOLS"."CLIENTE" TO "DBL_BI_ODI";
GRANT SELECT ON "SCCTOOLS"."EMPRESA" TO "DBL_BI_ODI";
GRANT SELECT ON "SCCTOOLS"."PRODUTO" TO "DBL_BI_ODI";
GRANT SELECT ON "SCCTOOLS"."CONTRATO" TO "DBL_BI_ODI";
GRANT SELECT ON "SCCTOOLS"."FILIAL" TO "DBL_BI_ODI";
GRANT SELECT ON "SCCTOOLS"."CONTRATO_EXTENSAO" TO "DBL_BI_ODI";
GRANT SELECT ON "SCCTOOLS"."LOJA" TO "DBL_BI_ODI";


GRANT "CONNECT" TO "DBLINK_RACFINL_OU_FINHOMO11G";
GRANT CREATE SESSION TO "DBLINK_RACFINL_OU_FINHOMO11G";
GRANT SELECT ON "SUPORTERJ"."BCSUL_T_RISK_EMPRESA" TO "DBLINK_RACFINL_OU_FINHOMO11G";
GRANT SELECT ON "SUPORTERJ"."BCSUL_V_RET_LOTE_REPRESADOS" TO "DBLINK_RACFINL_OU_FINHOMO11G";


GRANT CREATE SESSION TO "DBLINK_TOOLSH";

GRANT "CONNECT" TO "FIX_FECH";
GRANT "RESOURCE" TO "FIX_FECH";
GRANT CREATE TABLE TO "FIX_FECH";
GRANT UNLIMITED TABLESPACE TO "FIX_FECH";

GRANT CREATE SESSION TO "IFRS_USER";

GRANT "CONNECT" TO "INTEGRADOR" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "INTEGRADOR" WITH ADMIN OPTION;
GRANT "CONNECT_10G" TO "INTEGRADOR";
GRANT "PLUSTRACE" TO "INTEGRADOR";
GRANT CREATE JOB TO "INTEGRADOR";
GRANT CREATE ANY MATERIALIZED VIEW TO "INTEGRADOR";
GRANT CREATE PROCEDURE TO "INTEGRADOR";
GRANT FORCE ANY TRANSACTION TO "INTEGRADOR";
GRANT CREATE VIEW TO "INTEGRADOR";
GRANT CREATE SYNONYM TO "INTEGRADOR";
GRANT ALTER ANY INDEX TO "INTEGRADOR";
GRANT UPDATE ANY TABLE TO "INTEGRADOR";
GRANT INSERT ANY TABLE TO "INTEGRADOR";
GRANT SELECT ANY TABLE TO "INTEGRADOR";
GRANT LOCK ANY TABLE TO "INTEGRADOR";
GRANT DROP ANY TABLE TO "INTEGRADOR";
GRANT ALTER ANY TABLE TO "INTEGRADOR";
GRANT CREATE ANY TABLE TO "INTEGRADOR";
GRANT CREATE TABLE TO "INTEGRADOR";
GRANT UNLIMITED TABLESPACE TO "INTEGRADOR" WITH ADMIN OPTION;
GRANT ALTER SESSION TO "INTEGRADOR" WITH ADMIN OPTION;


GRANT "CONNECT" TO "INTEGRADOR_JOBS";
GRANT "RESOURCE" TO "INTEGRADOR_JOBS";
GRANT "CONNECT_10G" TO "INTEGRADOR_JOBS";
GRANT "PLUSTRACE" TO "INTEGRADOR_JOBS";
GRANT CREATE JOB TO "INTEGRADOR_JOBS";
GRANT DEBUG CONNECT SESSION TO "INTEGRADOR_JOBS";
GRANT CREATE ANY MATERIALIZED VIEW TO "INTEGRADOR_JOBS";
GRANT CREATE DATABASE LINK TO "INTEGRADOR_JOBS";
GRANT CREATE SYNONYM TO "INTEGRADOR_JOBS";
GRANT SELECT ANY TABLE TO "INTEGRADOR_JOBS";
GRANT CREATE TABLE TO "INTEGRADOR_JOBS";
GRANT UNLIMITED TABLESPACE TO "INTEGRADOR_JOBS";
GRANT ALTER SESSION TO "INTEGRADOR_JOBS";


GRANT "CONNECT" TO "LK_BIRAC_IFRS";
GRANT CREATE SESSION TO "LK_BIRAC_IFRS";


GRANT "CONNECT" TO "LK_C3_TOOLS";
GRANT CREATE SESSION TO "LK_C3_TOOLS";


GRANT CREATE DATABASE LINK TO "LK_COMISSAOH";
GRANT CREATE SYNONYM TO "LK_COMISSAOH";
GRANT CREATE SESSION TO "LK_COMISSAOH";

GRANT "CONNECT" TO "LK_IFRS_SCCTOOLS";


GRANT "CONNECT" TO "LK_MIS";


GRANT "CONNECT" TO "LK_MIS_TOOLS";
GRANT CREATE SESSION TO "LK_MIS_TOOLS";


GRANT "CONNECT" TO "LK_RISCO";
GRANT CREATE SESSION TO "LK_RISCO";


GRANT "RL_SUPORTE_TI" TO "LK_SUPORTE_TI";
GRANT CREATE SESSION TO "LK_SUPORTE_TI";

GRANT SELECT ANY TABLE TO "LK_TOOLS_BACEN";
GRANT CREATE SESSION TO "LK_TOOLS_BACEN";

GRANT CREATE SESSION TO "LK_TOOLS_C3";

GRANT CREATE SESSION TO "LK_TOOLS_C3PROD";

GRANT CREATE SESSION TO "LK_TOOLSPP";

GRANT "CONNECT" TO "MONITORIA";
GRANT "RESOURCE" TO "MONITORIA";
GRANT "SELECT_CATALOG_ROLE" TO "MONITORIA";
GRANT "DBA_PROD" TO "MONITORIA";
GRANT MANAGE SCHEDULER TO "MONITORIA";
GRANT CREATE JOB TO "MONITORIA";
GRANT ANALYZE ANY DICTIONARY TO "MONITORIA";
GRANT ANALYZE ANY TO "MONITORIA";
GRANT SELECT ANY TABLE TO "MONITORIA";
GRANT UNLIMITED TABLESPACE TO "MONITORIA";
GRANT ALTER SYSTEM TO "MONITORIA";


GRANT "DBA" TO "MONITORIA_CONTINGENCIA";
GRANT "DBA_PROD" TO "MONITORIA_CONTINGENCIA";
GRANT UNLIMITED TABLESPACE TO "MONITORIA_CONTINGENCIA";


GRANT "CONNECT" TO "NETBACKUP";
GRANT "RECOVERY_CATALOG_OWNER" TO "NETBACKUP";
GRANT "AQ_ADMINISTRATOR_ROLE" TO "NETBACKUP";
GRANT UNLIMITED TABLESPACE TO "NETBACKUP";


GRANT "CONNECT" TO "ODI";
GRANT "RESOURCE" TO "ODI";
GRANT "CONNECT_10G" TO "ODI";
GRANT UNLIMITED TABLESPACE TO "ODI";


GRANT "CONNECT" TO "ODI_TMP";
GRANT "RL_SCCTOOLS_SELECT" TO "ODI_TMP";
GRANT "RL_SUPORTERJ_SELECT" TO "ODI_TMP";
GRANT CREATE PROCEDURE TO "ODI_TMP";
GRANT CREATE TABLE TO "ODI_TMP";
GRANT UNLIMITED TABLESPACE TO "ODI_TMP";


GRANT "CONNECT" TO "R_STATS";
GRANT "RESOURCE" TO "R_STATS";
GRANT "RL_SUPORTE_TI" TO "R_STATS";
GRANT SELECT ANY TABLE TO "R_STATS";
GRANT UNLIMITED TABLESPACE TO "R_STATS";


GRANT "CONNECT" TO "RAET_INQUERITO";
GRANT "RESOURCE" TO "RAET_INQUERITO";
GRANT UNLIMITED TABLESPACE TO "RAET_INQUERITO";


GRANT "CONNECT" TO "RENT";
GRANT SELECT ON "SCCTOOLS"."SCC_CONTRATO_C3" TO "RENT";


GRANT "CONNECT" TO "SCC3533";
GRANT "RESOURCE" TO "SCC3533";
GRANT "CONNECT_10G" TO "SCC3533";
GRANT CREATE ANY PROCEDURE TO "SCC3533";
GRANT FORCE TRANSACTION TO "SCC3533";
GRANT CREATE VIEW TO "SCC3533";
GRANT CREATE ANY SYNONYM TO "SCC3533";
GRANT CREATE ANY INDEX TO "SCC3533";
GRANT DELETE ANY TABLE TO "SCC3533";
GRANT DROP ANY TABLE TO "SCC3533";
GRANT CREATE ANY TABLE TO "SCC3533";
GRANT UNLIMITED TABLESPACE TO "SCC3533";
GRANT CREATE SESSION TO "SCC3533";

GRANT "CONNECT" TO "SCCJUN";
GRANT "RESOURCE" TO "SCCJUN";
GRANT "SELECT_CATALOG_ROLE" TO "SCCJUN";
GRANT "IMP_FULL_DATABASE" TO "SCCJUN";
GRANT "CONNECT_10G" TO "SCCJUN";
GRANT "TEMP_VIEWS_SELECT" TO "SCCJUN";
GRANT "QUEST_SL_SQLAB_ROLE" TO "SCCJUN";
GRANT SELECT ANY DICTIONARY TO "SCCJUN";
GRANT CREATE ANY DIRECTORY TO "SCCJUN";
GRANT CREATE MATERIALIZED VIEW TO "SCCJUN";
GRANT EXECUTE ANY PROCEDURE TO "SCCJUN";
GRANT CREATE PUBLIC SYNONYM TO "SCCJUN";
GRANT DROP ANY SYNONYM TO "SCCJUN";
GRANT CREATE ANY SYNONYM TO "SCCJUN";
GRANT CREATE SYNONYM TO "SCCJUN";
GRANT SELECT ANY TABLE TO "SCCJUN";
GRANT DROP ANY TABLE TO "SCCJUN";
GRANT CREATE ANY TABLE TO "SCCJUN";
GRANT UNLIMITED TABLESPACE TO "SCCJUN";
GRANT RESTRICTED SESSION TO "SCCJUN";
GRANT ALTER SESSION TO "SCCJUN";


GRANT "CONNECT" TO "SCCTOOLS" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "SCCTOOLS" WITH ADMIN OPTION;
GRANT "SELECT_CATALOG_ROLE" TO "SCCTOOLS";
GRANT "IMP_FULL_DATABASE" TO "SCCTOOLS";
GRANT "CONNECT_10G" TO "SCCTOOLS";
GRANT "TEMP_VIEWS_SELECT" TO "SCCTOOLS";
GRANT "QUEST_SL_SQLAB_ROLE" TO "SCCTOOLS";
GRANT DEBUG ANY PROCEDURE TO "SCCTOOLS";
GRANT DEBUG CONNECT SESSION TO "SCCTOOLS";
GRANT SELECT ANY DICTIONARY TO "SCCTOOLS";
GRANT CREATE MATERIALIZED VIEW TO "SCCTOOLS";
GRANT EXECUTE ANY PROCEDURE TO "SCCTOOLS";
GRANT CREATE VIEW TO "SCCTOOLS";
GRANT CREATE PUBLIC SYNONYM TO "SCCTOOLS";
GRANT DROP ANY SYNONYM TO "SCCTOOLS";
GRANT CREATE ANY SYNONYM TO "SCCTOOLS";
GRANT CREATE SYNONYM TO "SCCTOOLS";
GRANT SELECT ANY TABLE TO "SCCTOOLS";
GRANT DROP ANY TABLE TO "SCCTOOLS";
GRANT CREATE ANY TABLE TO "SCCTOOLS";
GRANT UNLIMITED TABLESPACE TO "SCCTOOLS";
GRANT RESTRICTED SESSION TO "SCCTOOLS";
GRANT ALTER SESSION TO "SCCTOOLS";


GRANT "CONNECT" TO "SCCTOOLS_JOBS";
GRANT "RESOURCE" TO "SCCTOOLS_JOBS";
GRANT "SELECT_CATALOG_ROLE" TO "SCCTOOLS_JOBS";
GRANT "IMP_FULL_DATABASE" TO "SCCTOOLS_JOBS";
GRANT "CONNECT_10G" TO "SCCTOOLS_JOBS";
GRANT "TEMP_VIEWS_SELECT" TO "SCCTOOLS_JOBS";
GRANT "QUEST_SL_SQLAB_ROLE" TO "SCCTOOLS_JOBS";
GRANT DEBUG CONNECT SESSION TO "SCCTOOLS_JOBS";
GRANT ALTER ANY MATERIALIZED VIEW TO "SCCTOOLS_JOBS";
GRANT CREATE ANY MATERIALIZED VIEW TO "SCCTOOLS_JOBS";
GRANT CREATE MATERIALIZED VIEW TO "SCCTOOLS_JOBS";
GRANT CREATE DATABASE LINK TO "SCCTOOLS_JOBS";
GRANT CREATE PUBLIC SYNONYM TO "SCCTOOLS_JOBS";
GRANT CREATE SYNONYM TO "SCCTOOLS_JOBS";
GRANT SELECT ANY TABLE TO "SCCTOOLS_JOBS";
GRANT UNLIMITED TABLESPACE TO "SCCTOOLS_JOBS";
GRANT RESTRICTED SESSION TO "SCCTOOLS_JOBS";
GRANT ALTER SESSION TO "SCCTOOLS_JOBS";


GRANT "CONNECT" TO "SCQ_HOMOLOG";
GRANT "RESOURCE" TO "SCQ_HOMOLOG";
GRANT "RL_SUPORTERJ_SELECT" TO "SCQ_HOMOLOG";
GRANT "RL_SUPORTE_TI_DML" TO "SCQ_HOMOLOG";
GRANT "RL_SUPORTE_TI_EXEC" TO "SCQ_HOMOLOG";
GRANT DEBUG ANY PROCEDURE TO "SCQ_HOMOLOG";
GRANT DEBUG CONNECT SESSION TO "SCQ_HOMOLOG";
GRANT CREATE ANY SEQUENCE TO "SCQ_HOMOLOG";
GRANT CREATE ANY VIEW TO "SCQ_HOMOLOG";
GRANT UNLIMITED TABLESPACE TO "SCQ_HOMOLOG";


GRANT "CONNECT" TO "SISTESPROD";
GRANT "RESOURCE" TO "SISTESPROD";
GRANT "CONNECT_10G" TO "SISTESPROD";
GRANT "QUEST_SL_SQLAB_ROLE" TO "SISTESPROD";
GRANT UNLIMITED TABLESPACE TO "SISTESPROD";


GRANT "CONNECT" TO "SQL_GERENCIAL";
GRANT "RL_SCCTOOLS_SELECT" TO "SQL_GERENCIAL";
GRANT "RL_SUPORTERJ_SELECT" TO "SQL_GERENCIAL";
GRANT UNLIMITED TABLESPACE TO "SQL_GERENCIAL";


GRANT ALTER ANY MATERIALIZED VIEW TO "SQLGERENCIAL";
GRANT CREATE ANY MATERIALIZED VIEW TO "SQLGERENCIAL";
GRANT CREATE MATERIALIZED VIEW TO "SQLGERENCIAL";
GRANT CREATE PROCEDURE TO "SQLGERENCIAL";
GRANT CREATE VIEW TO "SQLGERENCIAL";
GRANT CREATE SYNONYM TO "SQLGERENCIAL";
GRANT CREATE ANY TABLE TO "SQLGERENCIAL";
GRANT UNLIMITED TABLESPACE TO "SQLGERENCIAL";
GRANT CREATE SESSION TO "SQLGERENCIAL";


GRANT "CONNECT" TO "SUPORTERJ";
GRANT "RESOURCE" TO "SUPORTERJ";
GRANT "DBA" TO "SUPORTERJ";
GRANT "CONNECT_10G" TO "SUPORTERJ";
GRANT "TEMP_VIEWS_SELECT" TO "SUPORTERJ";
GRANT "QUEST_SL_SQLAB_ROLE" TO "SUPORTERJ";
GRANT CREATE JOB TO "SUPORTERJ";
GRANT DEBUG ANY PROCEDURE TO "SUPORTERJ";
GRANT DEBUG CONNECT SESSION TO "SUPORTERJ";
GRANT SELECT ANY DICTIONARY TO "SUPORTERJ";
GRANT CREATE ANY DIRECTORY TO "SUPORTERJ";
GRANT ALTER ANY MATERIALIZED VIEW TO "SUPORTERJ";
GRANT CREATE ANY MATERIALIZED VIEW TO "SUPORTERJ";
GRANT CREATE MATERIALIZED VIEW TO "SUPORTERJ";
GRANT CREATE TRIGGER TO "SUPORTERJ";
GRANT CREATE VIEW TO "SUPORTERJ";
GRANT CREATE PUBLIC SYNONYM TO "SUPORTERJ";
GRANT CREATE SYNONYM TO "SUPORTERJ";
GRANT SELECT ANY TABLE TO "SUPORTERJ" WITH ADMIN OPTION;
GRANT CREATE TABLE TO "SUPORTERJ";
GRANT UNLIMITED TABLESPACE TO "SUPORTERJ";
GRANT ALTER SESSION TO "SUPORTERJ";
GRANT CREATE SESSION TO "SUPORTERJ";


GRANT "CONNECT" TO "SUPORTERJ_JOBS";
GRANT "RESOURCE" TO "SUPORTERJ_JOBS";
GRANT "CONNECT_10G" TO "SUPORTERJ_JOBS";
GRANT "TEMP_VIEWS_SELECT" TO "SUPORTERJ_JOBS";
GRANT "QUEST_SL_SQLAB_ROLE" TO "SUPORTERJ_JOBS";
GRANT CREATE JOB TO "SUPORTERJ_JOBS";
GRANT ADMINISTER DATABASE TRIGGER TO "SUPORTERJ_JOBS";
GRANT ALTER ANY MATERIALIZED VIEW TO "SUPORTERJ_JOBS";
GRANT CREATE ANY MATERIALIZED VIEW TO "SUPORTERJ_JOBS";
GRANT CREATE MATERIALIZED VIEW TO "SUPORTERJ_JOBS";
GRANT CREATE PUBLIC DATABASE LINK TO "SUPORTERJ_JOBS";
GRANT CREATE DATABASE LINK TO "SUPORTERJ_JOBS";
GRANT CREATE VIEW TO "SUPORTERJ_JOBS";
GRANT CREATE PUBLIC SYNONYM TO "SUPORTERJ_JOBS";
GRANT CREATE SYNONYM TO "SUPORTERJ_JOBS";
GRANT SELECT ANY TABLE TO "SUPORTERJ_JOBS";
GRANT CREATE TABLE TO "SUPORTERJ_JOBS";
GRANT ALTER SESSION TO "SUPORTERJ_JOBS";


GRANT "CONNECT" TO "TOOLS" WITH ADMIN OPTION;
GRANT "RESOURCE" TO "TOOLS" WITH ADMIN OPTION;
GRANT "CONNECT_10G" TO "TOOLS";
GRANT "QUEST_SL_SQLAB_ROLE" TO "TOOLS";
GRANT CREATE ANY SYNONYM TO "TOOLS";
GRANT CREATE TABLE TO "TOOLS";
GRANT UNLIMITED TABLESPACE TO "TOOLS" WITH ADMIN OPTION;


GRANT CREATE PROCEDURE TO "TRIBUTOSMIU";
GRANT CREATE TABLE TO "TRIBUTOSMIU";
GRANT UNLIMITED TABLESPACE TO "TRIBUTOSMIU";
GRANT CREATE SESSION TO "TRIBUTOSMIU";

GRANT "CONNECT" TO "ZABBIX";
GRANT SELECT ANY DICTIONARY TO "ZABBIX";
GRANT CREATE SESSION TO "ZABBIX";