set pages 999 feedback on timing on echo on
spool grants.log

--FINPAC
GRANT SELECT ON V_$LOCK  TO FINPAC;
GRANT SELECT ON SYS.OBJ$ TO FINPAC;
GRANT EXECUTE ON DBMS_LOCK TO FINPAC;
GRANT EXECUTE ON DBMS_LOCK TO FINPAC;
GRANT SELECT ON V_$SESSION TO FINPAC;
GRANT SELECT ON V_$PARAMETER TO FINPAC;
GRANT EXECUTE ON SYS.DBMS_PIPE TO FINPAC;

--FINPAC_CUSTOM
GRANT EXECUTE ON SYS.DBMS_PIPE TO FINPAC_CUSTOM;

--MIDDLE
GRANT SELECT ON V_$SESSION TO MIDDLE;

--NETBACKUP
GRANT UNLIMITED TABLESPACE TO NETBACKUP;
GRANT AQ_ADMINISTRATOR_ROLE TO NETBACKUP;
GRANT CONNECT TO NETBACKUP;
GRANT RECOVERY_CATALOG_OWNER TO NETBACKUP;

--SDBANCO
GRANT CREATE SYNONYM TO SDBANCO;
GRANT ALL ON SDIMIO.SD_SUB_SIS TO SDBANCO;
GRANT SELECT ON SYS.OBJ$ TO SDBANCO;
GRANT EXECUTE ON DBMS_LOCK TO SDBANCO;
GRANT AQ_ADMINISTRATOR_ROLE TO SDBANCO;
GRANT EXECUTE ON DBMS_AQADM TO SDBANCO;
GRANT EXECUTE ON DBMS_MONITOR TO SDBANCO;
GRANT EXECUTE ON SYS.DBMS_PIPE TO SDBANCO;
GRANT CREATE MATERIALIZED VIEW TO SDBANCO;

--SDIMIO
GRANT EXECUTE ON DBMS_AQ TO SDIMIO;
GRANT SELECT ON SYS.OBJ$ TO SDIMIO;
GRANT EXECUTE ON DBMS_AQADM TO SDIMIO;
GRANT EXECUTE ON SYS.DBMS_PIPE TO SDIMIO;

--GRANTS TO ROLES
GRANT SELECT ON SYS.OBJ$ TO SD_ROLE;
GRANT SELECT ON SYS.OBJ$ TO FN_ROLE;
GRANT SELECT ON SYS.OBJ$ TO BC_ROLE;

spool off