
   CREATE USER "SCA" IDENTIFIED BY VALUES '7ED8ECE4E517CD8D'
      DEFAULT TABLESPACE "CARTAO_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "SUPORTERJ" IDENTIFIED BY VALUES 'C893884F01CC52CA'
      DEFAULT TABLESPACE "CARTAO_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "CARTAO" IDENTIFIED BY VALUES 'D09D1B6BDFCEC02C'
      DEFAULT TABLESPACE "CARTAO_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "LK_CARTAO_BINOVO" IDENTIFIED BY VALUES 'CA6C742C05A795B1'
      DEFAULT TABLESPACE "CARTAO_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "RETAGUARDA_JOBS" IDENTIFIED BY VALUES '71B6B11F6278422E'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "LK_CONSIG" IDENTIFIED BY VALUES 'C20CB686CAB0F2EB'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "SCPTOOLS" IDENTIFIED BY VALUES '0D96AEBFDB18DA9C'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "LK_CARTAO" IDENTIFIED BY VALUES 'D6610156390AD019'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "LK_MIS" IDENTIFIED BY VALUES 'B754F590D9A5FE9E'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "RETAG_INSS" IDENTIFIED BY VALUES '588008D9A215DD2B'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "DBLINK_TOOLSH" IDENTIFIED BY VALUES '020A1336486CE44C'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "RETAGUARDA" IDENTIFIED BY VALUES '9C36D1ECA24F6A32'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "LK_MIS_RETAG" IDENTIFIED BY VALUES '5E572C25C94EF453'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "NETBACKUP" IDENTIFIED BY VALUES '9DBA906975B4978B'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "DBLINK_FINHOMO11G" IDENTIFIED BY VALUES '8DBE9405FDEC6291'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "LK_SUPORTE_TI" IDENTIFIED BY VALUES '6650045AD5945D6F'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "SCPTOOLS1" IDENTIFIED BY VALUES '8820F54838ED87FD'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



   CREATE USER "TOOLS" IDENTIFIED BY VALUES 'D74E4D91DEEC2AE2'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY"
      ACCOUNT LOCK;



   CREATE USER "DBL_BI_ODI" IDENTIFIED BY VALUES '7AE8B31AFECA8B93'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY"
      ACCOUNT LOCK;



  DECLARE
  TEMP_COUNT NUMBER;
  SQLSTR VARCHAR2(200);
BEGIN
  SQLSTR := 'ALTER USER "RETAG_INSS" QUOTA UNLIMITED ON "RETAG_DADOS"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES
              WHERE TABLESPACE_NAME = ''RETAG_DADOS'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN;
      ELSE RAISE;
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/

  DECLARE
  TEMP_COUNT NUMBER;
  SQLSTR VARCHAR2(200);
BEGIN
  SQLSTR := 'ALTER USER "RETAG_INSS" QUOTA UNLIMITED ON "RETAG_INDICES"';
  EXECUTE IMMEDIATE SQLSTR;
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE = -30041 THEN
      SQLSTR := 'SELECT COUNT(*) FROM USER_TABLESPACES
              WHERE TABLESPACE_NAME = ''RETAG_INDICES'' AND CONTENTS = ''TEMPORARY''';
      EXECUTE IMMEDIATE SQLSTR INTO TEMP_COUNT;
      IF TEMP_COUNT = 1 THEN RETURN;
      ELSE RAISE;
      END IF;
    ELSE
      RAISE;
    END IF;
END;
/



   GRANT "RCARTAO" TO "SCA";



  GRANT CREATE TRIGGER TO "SCA";

  GRANT CREATE SYNONYM TO "SCA";

  GRANT CREATE TABLE TO "SCA";

  GRANT UNLIMITED TABLESPACE TO "SCA";

  GRANT CREATE SESSION TO "SCA";



  GRANT SELECT ON "SYS"."V_$SESSION" TO "RETAGUARDA";

  GRANT SELECT ON "SYS"."V_$SQL" TO "RETAGUARDA";

  GRANT SELECT ON "SYS"."GV_$SESSION" TO "RETAGUARDA";

  GRANT SELECT ON "SYS"."GV_$LOCKED_OBJECT" TO "RETAGUARDA";

  GRANT SELECT ON "SYS"."GV_$SQL" TO "RETAGUARDA";

  GRANT SELECT ON "SYS"."FLASHBACK_TRANSACTION_QUERY" TO "RETAGUARDA";

  GRANT SELECT ON "SYS"."DBA_JOBS" TO "RETAGUARDA";

  GRANT EXECUTE ON "SYS"."UTL_FILE" TO "RETAGUARDA";

  GRANT ALTER ON "RETAGUARDA"."BCSUL_SEQ_ARQ_INSS_BCS" TO "RETAGUARDA";

  GRANT SELECT ON "RETAGUARDA"."BCSUL_SEQ_ARQ_INSS_BCS" TO "RETAGUARDA";

  GRANT ALTER ON "RETAGUARDA"."BCSUL_SEQ_PROX_PROP_SCP" TO "RETAGUARDA";

  GRANT SELECT ON "RETAGUARDA"."BCSUL_SEQ_PROX_PROP_SCP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_FILTRO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_CONCILIA_ARQUIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_PAGAMENTOS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RET_ATU" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."FORMATA_NUM" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_SITUACAO_CANC" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."IN_DINAMICO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_REMOVE_CARACTER" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."FORMATA_ALFA" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS"."ACERTA_DT_PRECONTRATO" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS"."BCSUL_P_CONTRATO_DUPLICADO" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS"."SP_GERA_BORDERO" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS"."SP_GERA_ARQUIVO_CARGA_SCP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ACERTO_RENEG" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ACE_GERA_ARQUIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ATU_BASE_POSITIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ATU_BF_SEM_BD_MARGEM" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_CARGA_ARQ_ANT_TABELA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_CARGA_ARQ_ANTIGOS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_CANC_PROP_WS_ESCR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_CARTAO_CANC" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_AUDIT_LOG" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ATU_PROP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ATU_PERIODICAS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ATU_PENDENCIA_FISICO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ATU_FAIXA_CEP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CALCULO_IOF" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RECALC_IOF" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_COMISSAO_PROPOSTA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_LOG_PROPOSTA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."TIRAACENTO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_INSERIR_CANC_TRT_MG" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_CPF_FRAUDE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_CARREGA_LOJAS_INSS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_CARGA_AUDITORIA_RENEG" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_CARGA_AVERBADO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_ROTINAS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_CARGA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_CALCULA_ULTI_VCT" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_CANC_PROP_DEV" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_ARQ_BAIXA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_APOIO_JUR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_ANALISE_IOF" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_ANALISE_CONCILIA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_ATU_SCP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_REL_DOC_TED_DEVOLV" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_AJUSTA_TUDO_CRIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_TRATA_AGENCIA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."PROC_JOB67" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CRIVO_CONTROLE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."P" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."DT_SETPROPERTYBYID" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."DT_DROPUSEROBJECTBYID" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_WEB_PROP_ATUALIZACAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_WEB_PROPOSTAS_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."SP_ATUALIZABORDEROPROCESSADO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."TMP_F_ATU_REEMB_INSS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_REEMBOLSO_INSS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_TRATA_AGENCIA_NEW" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_TRATA_AGENCIA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_MSG_30" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_ENVIA_EMAIL_TESTE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_ENVIA_EMAIL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_CRIVO_MANUAL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SP_CARTAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CRIVO_MANUAL_CARTAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_WEB_PROP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_VALIDA_BORDERO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_VALIDA_ALCADA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_TMP_MIGRA_PF" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_SISCREV_GRAVALOG" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_SISCREV_ALT_OMNI" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_NEGA_MANUALMENTE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_MONTA_BAIXA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_INFORMATIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_PERIODO_INSS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RETORNA_DIA_UTIL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_IMPORTA_OP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_CONCILIA_ERRO_INSS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RET_CF_OU_CM" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_CARGA_SCP_XIII" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_CARGA_SCP_MIDDLE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RET_CARGA_SCP" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS"."BCSUL_PCK_INTEGRA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."IS_NUMBER" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_INDEXADOR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_CORRECAO_INDEXADOR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_RECALC_VALORES" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ATU_BF_SEM_BD" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ATU_AVERBADO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_P_ACE_DADOS_ARQUIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."AVC_P_INSERE_RENEG_A28" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS"."SP_GERA_ARQUIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS"."FORMATA_NUM" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS"."FORMATA_ALFA" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."F_RETORNACONTRATO" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_F_ANT_DIAUTIL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SPLIT" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."LU_F_NUM_DIAS_UTEIS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_DIAUTIL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."F_CALCULA_VALOR_A_LIBERAR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."FINAC_CLIENTE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."EXTENSO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."DT_ADDUSEROBJECT" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."CLIENTE_PAGO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."CCC_F_SEQ_ARQ_INSS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_CEP_UF" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_ANT_DIAUTIL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_AJUST_REEMB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_360_DIAS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."ACERTA_STRING" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RENEG_2_OU_2F" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_REMOVE_CARACTER2" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_PROX_VCT" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_PROX_DIAUTIL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_PAR_OU_IMPAR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_NUM_DIAS_UTEIS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_IOF" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_WEB_OP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_VCT_BRADESCO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_VAL_PRT" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_VALOR_PRESENTE_360" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_VALOR_PRESENTE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_SEG_HORA_STR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RET_PASSA_BAT_FISICO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RET_FPGTO_CLI" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RET_CALC_PRIM_VCT_TMP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RET_ARQ" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_RETORNA_CONTRATO_LOJA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_FORMA_PGTO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_FORMATA_INSCRICAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_FINAC_CLIENTE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_DIF_HORA_STR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_F_DIA_SEMANA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."ACOES_PROPOSTA_MANUAL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_AJUSTE_ATU_MARGEM" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_ALTER_DADOS_CRIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_ANALISE_IMP_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_ATUALIZA_CEP_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_ARQ_BAIXA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_ANALISE_PROPOSTA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_ACOES_PROPOSTA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_ACERTA_CRITICAS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_REL_DOC_TED_DEVOLV" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_REE_PAGAMENTOS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CRIVO_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_CONCILIA_PAGOS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_COMPRA_GUARULHOS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_COMPRA_BEM" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_CIV" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_AVERB_TJ_MG" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_AVERBAR" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."SCS_PCK_V_TESTE_PROV_NOVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_UTIL" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_REL_COMPRA_CARTEIRA" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_CONCILIACAO_ADQ" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_BAIXA_CONSIG_OLD" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_BAIXA_CONSIG" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_BAIXAS_CEDENTE" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_BAIXAS" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_AQUISICAO_CARTEIRA" TO "RETAGUARDA";

  GRANT EXECUTE ON "SCPTOOLS1"."BCSUL_PCK_AQUISICAO_CARTAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "PREV"."BCSUL_PCK_WEBPREV" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SFA_PCK_BCSUL_T_BAT_RENEG" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."SCS_PCK_V_TESTE_PROV_NOVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."PTOOLS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_WS_REL_ESCRITORIOS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_SCF_INTEGRACAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_ROBO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_UPD_CONFERENCIA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_TOSHIBA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_REAPRESENTACAO_B" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_REAPRESENTACAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_PAGAMENTOSB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_MATERA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_LIMITE_CREDITO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_IMPORTACAOB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_IMPORTACAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_GOV_SP_IMP_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_GOV_SP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_CRIVO_MONITOR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_CRIA_NOVA_PROP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_CONTROLE_COMPRAB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_CONTROLE_COMPRA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_RET_CONCILIA_PREV" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CRIVO_MANUAL" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CRIVO_CONTROLEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CONFERENCIA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CAMPANHA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_REE_CRITICAS" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_REE_CONTROLE" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_PROVIDER" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_POPULA_STAGE_CPP" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_METODOS_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_MATERA" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_ENVIA_EMAIL_ANEXO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CRIVO_WEB_PAR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_CRIVO_WEB_IMPAR" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_BUSCA_JURIDICO" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."BCSUL_PCK_ATU_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "RETAGUARDA"."ANALISE_BASE_CRIVO" TO "RETAGUARDA";

  GRANT SELECT ON "CARTAO"."CCC_C18_EMPRESAS" TO "RETAGUARDA";

  GRANT SELECT ON "CARTAO"."CCC_C25_CLIENTES" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_PCK_GENERICO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_POPULA_RBI" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."ACERTA_CD_ANALISE" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_P_ATU_BLOQUEIO_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."POPULA_TEMP" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."TEMP_EXP_ARQUIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."TEMP_EXP_ARQUIVO_REPRESENTANTE" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_CONTA_ALTERNATIVA" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."TEMP_CAMPANHA_TRAVE" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."TEMP_CAMPANHA_TRAVE_BONUS" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."TMP_UPD_PRRISCO_CONTA_RONALDO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."DPR_CLOBTOFILE" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CPP" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."ACERTA_CONTA_CARTAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_INCLUIR_CLIENTE_PREVIA" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_INSERE_CAMPANHA_2008" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."ENVIA_EMAIL_HTML" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_P_BACEN_RBI" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_P_BACEN_RISCO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_EMAIL_ALT_MARGEM" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_POPULA_PRRISCO_CONTA" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_P_BACEN_ANALISE_USO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_P_BACEN_RISCO_IAN" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_ATU_EMPRESA_MOTOBOY_WEB" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_P_BACEN_RISCO_ALAN" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_ACERTA_MATRICULA" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."ACERTA_DATA_ATRIBUICAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."TEMP_ATUALIZAR_CAMPANHA_ATIV" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_PCK_CAMPANHA_ATIVACAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_ACERTA_DATA_ATIVACAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."ACERTA_DATA_DESBLOQUEIO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_LIBERA_CARTAO_CANCEL" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_PCK_CANCEL_CARTAO_RETAG" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."ENVIA_EMAIL_IMPORTACAO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_MIGRA_CARTAO_CONSIG" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_IMPORTA_ARQUIVO_ICATU" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_ACERTA_CONTA" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."AVISA_CRIVO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."ANDREY" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_P_BAIXA_FISICO_MASSA" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."POPULA_PROPOSTAS_BASE_REFIN" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."INSERE_C113" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."INSERE_C112" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."PROXIMO_CLIENTE" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."FORMATA_ALFA" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."FORMATA_NUM" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."FC_VALIDA_CPF" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_F_RETORNA_CRITICA" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."TEMP_FRAUDE" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_F_DIF_HORA_STR" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."TMP_VERIFICA_ULT_STATUS" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_F_BUSCA_ST_ANT_DO_REP_1" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_F_NOME_CAMPOS_HEADER" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."CCC_F_BUSCA_VALOR_ALT_MARGEM" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."VERIFICA_CARTAO_VALIDO" TO "RETAGUARDA";

  GRANT EXECUTE ON "CARTAO"."BCSUL_F_TO_NUMBER" TO "RETAGUARDA";

  GR


   ALTER USER "SCPTOOLS1" DEFAULT ROLE ALL;


