
   CREATE USER "RETAGUARDA" IDENTIFIED BY VALUES '9C36D1ECA24F6A32'
      DEFAULT TABLESPACE "RETAG_DADOS"
      TEMPORARY TABLESPACE "TEMPORARY";



GRANT "CONNECT" TO "RETAGUARDA";

GRANT "RESOURCE" TO "RETAGUARDA";

GRANT "SELECT_CATALOG_ROLE" TO "RETAGUARDA";

GRANT "PLUSTRACE" TO "RETAGUARDA";



GRANT DEBUG ANY PROCEDURE TO "RETAGUARDA";

GRANT CREATE MATERIALIZED VIEW TO "RETAGUARDA";

GRANT CREATE PROCEDURE TO "RETAGUARDA";

GRANT CREATE VIEW TO "RETAGUARDA";

GRANT CREATE SYNONYM TO "RETAGUARDA";

GRANT SELECT ANY TABLE TO "RETAGUARDA";

GRANT CREATE ANY TABLE TO "RETAGUARDA";

GRANT CREATE TABLE TO "RETAGUARDA";

GRANT UNLIMITED TABLESPACE TO "RETAGUARDA";

GRANT ALTER SESSION TO "RETAGUARDA";


