spool create_tbls.log

set echo on
set timing on

CREATE BIGFILE TABLESPACE AUDITORIA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE AUDITORIA_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE AUDITORIA_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE CENTRAL_RISCO NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE FINPAC_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 15G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE FINPAC_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 25G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE INDICES_PART NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 50G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE INDICES_TEMP NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE MIDDLE_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE MIDDLE_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE MIO_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE MIO_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE SDBANCO_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 80G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE SDBANCO_DATA_GRANT NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 25G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE SDBANCO_DATA100 NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 30G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE SD_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 75G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE SD2_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 1G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE SPB_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE SPB_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE TABELAS_PART NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 10G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE TBS_DADOS_TMP NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 1G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE USER_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 100M AUTOEXTEND ON NEXT 100M;

spool off