spool roles.log
set echo on
CREATE ROLE SPDES_ROLE;
CREATE ROLE ACESSO_RM;
CREATE ROLE ACESSO_SDBANCO;
CREATE ROLE BC_ROLE;
CREATE ROLE DB_DBAS;
CREATE ROLE FN_ROLE;
CREATE ROLE SD_ROLE;
CREATE ROLE TC_ADMIN_ROLE;
CREATE ROLE TC_LDR_ROLE;
CREATE ROLE TC_MGR_ROLE;
CREATE ROLE RL_SUPORTE_TI_EXEC;
CREATE ROLE DBA_PROD;
CREATE ROLE RL_SUPORTE_TI;
CREATE ROLE RL_SUPORTE_TI_DML;
CREATE ROLE LG_ROLE;
CREATE ROLE PB_ROLE;
spool off