spool create_tbls.log

set echo on
set timing on

CREATE BIGFILE TABLESPACE AUDITORIA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE AUDITORIA_DATA NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE AUDITORIA_INDEX NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 500M AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE CARTAO_DADOS NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 5G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE CARTAO_INDICES NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 5G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE RETAG_DADOS NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 195G AUTOEXTEND ON NEXT 500M;
CREATE BIGFILE TABLESPACE RETAG_INDICES NOLOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO DATAFILE SIZE 59G AUTOEXTEND ON NEXT 500M;

spool off