spool roles.log
set echo on
CREATE ROLE RCARTAO;
CREATE ROLE DBA_PROD;
CREATE ROLE PLUSTRACE;
CREATE ROLE RL_ADM_CARTAO;
CREATE ROLE RL_SUPORTE_TI;
CREATE ROLE RL_SUPORTE_TI_DML;
CREATE ROLE RL_SUPORTE_TI_EXEC;

spool off