spool human_USERS.log
set echo on feedback on timing on

CREATE USER "PIERRE_RIBEIRO"  IDENTIFIED BY VALUES 'EE2EBD40697498B8' DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ;
CREATE USER "DIEGO_CABRAL" 	  IDENTIFIED BY VALUES 'A1FD3DD1890F5DF3' DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ;
CREATE USER "JOAO_ALVES" 	  IDENTIFIED BY VALUES '2FBCBCD3BE760797' DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ;
CREATE USER "IAN_CARVALHO" 	  IDENTIFIED BY VALUES 'F9524367364B596D' DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ;
CREATE USER "NELSON_CARVALHO" IDENTIFIED BY VALUES '8B9CF333069F43FC' DEFAULT TABLESPACE USERS TEMPORARY TABLESPACE TEMP ;

spool off