
  CREATE OR REPLACE PUBLIC SYNONYM "PROPOSTAS_BANCRED_COMPRA" FOR "RETAGUARDA"."PROPOSTAS_BANCRED_COMPRA";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_RET_GERARQ" FOR "RETAGUARDA"."BCSUL_T_RET_GERARQ";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_RET_CRIVO_LOG_ANALISE" FOR "RETAGUARDA"."BCSUL_T_RET_CRIVO_LOG_ANALISE";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_RET_STATUS_MOTIVO" FOR "RETAGUARDA"."BCSUL_T_RET_STATUS_MOTIVO";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_RET_INVALIDAS" FOR "RETAGUARDA"."BCSUL_T_RET_INVALIDAS";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_MV_ST_PROPOSTAS_WEB" FOR "RETAGUARDA"."BCSUL_MV_ST_PROPOSTAS_WEB";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_PROPOSTA_CRIVO" FOR "RETAGUARDA"."BCSUL_T_PROPOSTA_CRIVO";



  CREATE OR REPLACE PUBLIC SYNONYM "ACD_FAIXA_DESCONTO" FOR "SCPTOOLS"."ACD_FAIXA_DESCONTO";



  CREATE OR REPLACE PUBLIC SYNONYM "BATE_DADOS" FOR "SCPTOOLS"."BATE_DADOS";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_HEADER_ARQUIVOCARGA" FOR "SCPTOOLS"."BCSUL_T_HEADER_ARQUIVOCARGA";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_NUM_PROPOSTA_SCP" FOR "SCPTOOLS"."BCSUL_T_NUM_PROPOSTA_SCP";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_RISCOCREDITO" FOR "SCPTOOLS"."BCSUL_T_RISCOCREDITO";



  CREATE OR REPLACE PUBLIC SYNONYM "BCS_T_RISCOCREDITO_BK1" FOR "SCPTOOLS"."BCS_T_RISCOCREDITO_BK1";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_AGENCIASPOSTAIS" FOR "SCPTOOLS"."CEP_AGENCIASPOSTAIS";



  CREATE OR REPLACE PUBLIC SYNONYM "CERTO_SCPSCC" FOR "SCPTOOLS"."CERTO_SCPSCC";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_UNIDADEFEDERACAO" FOR "SCPTOOLS"."CEP_UNIDADEFEDERACAO";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_TPTLOGRADOUROS" FOR "SCPTOOLS"."CEP_TPTLOGRADOUROS";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_LOGRADOURO" FOR "SCPTOOLS"."CEP_LOGRADOURO";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_LOCALIDADES" FOR "SCPTOOLS"."CEP_LOCALIDADES";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_INI" FOR "SCPTOOLS"."CEP_INI";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_FXACEP" FOR "SCPTOOLS"."CEP_FXACEP";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_CODIGOSESPECIAIS" FOR "SCPTOOLS"."CEP_CODIGOSESPECIAIS";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_BAIRROS" FOR "SCPTOOLS"."CEP_BAIRROS";



  CREATE OR REPLACE PUBLIC SYNONYM "ETAPA" FOR "SCPTOOLS"."ETAPA";



  CREATE OR REPLACE PUBLIC SYNONYM "DICIONARIO" FOR "SCPTOOLS"."DICIONARIO";



  CREATE OR REPLACE PUBLIC SYNONYM "CONTRATOS_UPDATE" FOR "SCPTOOLS"."CONTRATOS_UPDATE";



  CREATE OR REPLACE PUBLIC SYNONYM "TAXA_MERCADO" FOR "SCPTOOLS"."TAXA_MERCADO";



  CREATE OR REPLACE PUBLIC SYNONYM "TAXA_FINANCEIRA" FOR "SCPTOOLS"."TAXA_FINANCEIRA";



  CREATE OR REPLACE PUBLIC SYNONYM "TAB_REF" FOR "SCPTOOLS"."TAB_REF";



  CREATE OR REPLACE PUBLIC SYNONYM "SCP_LOG_RETORNO_CRZ" FOR "SCPTOOLS"."SCP_LOG_RETORNO_CRZ";



  CREATE OR REPLACE PUBLIC SYNONYM "SCO_REGRA" FOR "SCPTOOLS"."SCO_REGRA";



  CREATE OR REPLACE PUBLIC SYNONYM "SCO_PARAM_DOMINIO" FOR "SCPTOOLS"."SCO_PARAM_DOMINIO";



  CREATE OR REPLACE PUBLIC SYNONYM "SCO_PARAM_ATRIBUTOS" FOR "SCPTOOLS"."SCO_PARAM_ATRIBUTOS";



  CREATE OR REPLACE PUBLIC SYNONYM "SCO_DOMINIO" FOR "SCPTOOLS"."SCO_DOMINIO";



  CREATE OR REPLACE PUBLIC SYNONYM "SCO_ATRIBUTOS" FOR "SCPTOOLS"."SCO_ATRIBUTOS";



  CREATE OR REPLACE PUBLIC SYNONYM "SCC_DBMS" FOR "SCPTOOLS"."SCC_DBMS";



  CREATE OR REPLACE PUBLIC SYNONYM "QUEST_TEMP_EXPLAIN" FOR "SCPTOOLS"."QUEST_TEMP_EXPLAIN";



  CREATE OR REPLACE PUBLIC SYNONYM "QUEST_COM_USER_PRIVILEGES" FOR "SCPTOOLS"."QUEST_COM_USER_PRIVILEGES";



  CREATE OR REPLACE PUBLIC SYNONYM "QUEST_COM_USERS" FOR "SCPTOOLS"."QUEST_COM_USERS";



  CREATE OR REPLACE PUBLIC SYNONYM "QUEST_COM_PRODUCT_PRIVS" FOR "SCPTOOLS"."QUEST_COM_PRODUCT_PRIVS";



  CREATE OR REPLACE PUBLIC SYNONYM "QUEST_COM_PRODUCTS_USED_BY" FOR "SCPTOOLS"."QUEST_COM_PRODUCTS_USED_BY";



  CREATE OR REPLACE PUBLIC SYNONYM "QUEST_COM_PRODUCTS" FOR "SCPTOOLS"."QUEST_COM_PRODUCTS";



  CREATE OR REPLACE PUBLIC SYNONYM "PRE_PARCELA" FOR "SCPTOOLS"."PRE_PARCELA";



  CREATE OR REPLACE PUBLIC SYNONYM "PRE_BORDERO" FOR "SCPTOOLS"."PRE_BORDERO";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_HIST_EXTENSAO_2" FOR "SCPTOOLS"."PRECONTRATO_HIST_EXTENSAO_2";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_HIST_EXTENSAO" FOR "SCPTOOLS"."PRECONTRATO_HIST_EXTENSAO";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_HIST_2" FOR "SCPTOOLS"."PRECONTRATO_HIST_2";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_HIST" FOR "SCPTOOLS"."PRECONTRATO_HIST";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_EXTENSAO_CRZ" FOR "SCPTOOLS"."PRECONTRATO_EXTENSAO_CRZ";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_EXTENSAO" FOR "SCPTOOLS"."PRECONTRATO_EXTENSAO";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_ETAPA_HIST_2" FOR "SCPTOOLS"."PRECONTRATO_ETAPA_HIST_2";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_ETAPA_HIST" FOR "SCPTOOLS"."PRECONTRATO_ETAPA_HIST";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_ETAPA" FOR "SCPTOOLS"."PRECONTRATO_ETAPA";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO_AVERBACAO" FOR "SCPTOOLS"."PRECONTRATO_AVERBACAO";



  CREATE OR REPLACE PUBLIC SYNONYM "PRECONTRATO" FOR "SCPTOOLS"."PRECONTRATO";



  CREATE OR REPLACE PUBLIC SYNONYM "PBCATVLD" FOR "SCPTOOLS"."PBCATVLD";



  CREATE OR REPLACE PUBLIC SYNONYM "PBCATTBL" FOR "SCPTOOLS"."PBCATTBL";



  CREATE OR REPLACE PUBLIC SYNONYM "PBCATFMT" FOR "SCPTOOLS"."PBCATFMT";



  CREATE OR REPLACE PUBLIC SYNONYM "PBCATEDT" FOR "SCPTOOLS"."PBCATEDT";



  CREATE OR REPLACE PUBLIC SYNONYM "PBCATCOL" FOR "SCPTOOLS"."PBCATCOL";



  CREATE OR REPLACE PUBLIC SYNONYM "PARAM_CFI" FOR "SCPTOOLS"."PARAM_CFI";



  CREATE OR REPLACE PUBLIC SYNONYM "CONTRATOS_N_ALTERADOS" FOR "SCPTOOLS"."CONTRATOS_N_ALTERADOS";



  CREATE OR REPLACE PUBLIC SYNONYM "CONTRATOS_DUPLICADOS" FOR "SCPTOOLS"."CONTRATOS_DUPLICADOS";



  CREATE OR REPLACE PUBLIC SYNONYM "CONFERE_DADOS" FOR "SCPTOOLS"."CONFERE_DADOS";



  CREATE OR REPLACE PUBLIC SYNONYM "CHEQUES_HIST_2" FOR "SCPTOOLS"."CHEQUES_HIST_2";



  CREATE OR REPLACE PUBLIC SYNONYM "CHEQUES_HIST" FOR "SCPTOOLS"."CHEQUES_HIST";



  CREATE OR REPLACE PUBLIC SYNONYM "CHEQUES" FOR "SCPTOOLS"."CHEQUES";



  CREATE OR REPLACE PUBLIC SYNONYM "CHAINED_ROWS" FOR "SCPTOOLS"."CHAINED_ROWS";



  CREATE OR REPLACE PUBLIC SYNONYM "MAQUINA" FOR "SCPTOOLS"."MAQUINA";



  CREATE OR REPLACE PUBLIC SYNONYM "LOG_CARGA" FOR "SCPTOOLS"."LOG_CARGA";



  CREATE OR REPLACE PUBLIC SYNONYM "INFO_BCB2" FOR "SCPTOOLS"."INFO_BCB2";



  CREATE OR REPLACE PUBLIC SYNONYM "INFO_BCB" FOR "SCPTOOLS"."INFO_BCB";



  CREATE OR REPLACE PUBLIC SYNONYM "IND_FINANCEIRO" FOR "SCPTOOLS"."IND_FINANCEIRO";



  CREATE OR REPLACE PUBLIC SYNONYM "IMPORTA" FOR "SCPTOOLS"."IMPORTA";



  CREATE OR REPLACE PUBLIC SYNONYM "NUM_CONTRATO" FOR "SCPTOOLS"."NUM_CONTRATO";



  CREATE OR REPLACE PUBLIC SYNONYM "MIGRA" FOR "SCPTOOLS"."MIGRA";



  CREATE OR REPLACE PUBLIC SYNONYM "CEP_AGENCIAISPOSTAIS" FOR "SCPTOOLS"."CEP_AGENCIAISPOSTAIS";



  CREATE OR REPLACE PUBLIC SYNONYM "BK_BORDERO" FOR "SCPTOOLS"."BK_BORDERO";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_RISCOCREDITO_AUX" FOR "SCPTOOLS"."BCSUL_T_RISCOCREDITO_AUX";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_HEADER_ARQUIVOCARGA_X" FOR "SCPTOOLS"."BCSUL_T_HEADER_ARQUIVOCARGA_X";



  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_T_RET_CARGA" FOR "SCPTOOLS"."BCSUL_T_RET_CARGA";


