
  CREATE OR REPLACE PUBLIC SYNONYM "BCSUL_V_RET_VALIDA_PARAMETROS" FOR "RETAGUARDA"."BCSUL_V_RET_VALIDA_PARAMETROS";



  CREATE OR REPLACE PUBLIC SYNONYM "CALENDARIO" FOR "SCPTOOLS"."CALENDARIO";



  CREATE OR REPLACE PUBLIC SYNONYM "EMPRESA_LOJA" FOR "SCPTOOLS"."EMPRESA_LOJA";



  CREATE OR REPLACE PUBLIC SYNONYM "EMPRESA_EMPRESA_BANCO" FOR "SCPTOOLS"."EMPRESA_EMPRESA_BANCO";



  CREATE OR REPLACE PUBLIC SYNONYM "EMPRESA_BANCO" FOR "SCPTOOLS"."EMPRESA_BANCO";



  CREATE OR REPLACE PUBLIC SYNONYM "EMPRESA" FOR "SCPTOOLS"."EMPRESA";



  CREATE OR REPLACE PUBLIC SYNONYM "FUNCAO" FOR "SCPTOOLS"."FUNCAO";



  CREATE OR REPLACE PUBLIC SYNONYM "FILIAL" FOR "SCPTOOLS"."FILIAL";



  CREATE OR REPLACE PUBLIC SYNONYM "USU_FUNCAO" FOR "SCPTOOLS"."USU_FUNCAO";



  CREATE OR REPLACE PUBLIC SYNONYM "USU_EMPRESA" FOR "SCPTOOLS"."USU_EMPRESA";



  CREATE OR REPLACE PUBLIC SYNONYM "TAC" FOR "SCPTOOLS"."TAC";



  CREATE OR REPLACE PUBLIC SYNONYM "TAB_TAXA" FOR "SCPTOOLS"."TAB_TAXA";



  CREATE OR REPLACE PUBLIC SYNONYM "TAB_FIN" FOR "SCPTOOLS"."TAB_FIN";



  CREATE OR REPLACE PUBLIC SYNONYM "PRODUTO" FOR "SCPTOOLS"."PRODUTO";



  CREATE OR REPLACE PUBLIC SYNONYM "CFI_USU" FOR "SCPTOOLS"."CFI_USU";



  CREATE OR REPLACE PUBLIC SYNONYM "LOJA_PRODUTO" FOR "SCPTOOLS"."LOJA_PRODUTO";



  CREATE OR REPLACE PUBLIC SYNONYM "LOJA" FOR "SCPTOOLS"."LOJA";



  CREATE OR REPLACE PUBLIC SYNONYM "AGENCIA" FOR "SCPTOOLS"."AGENCIA";



  CREATE OR REPLACE PUBLIC SYNONYM "BANCO" FOR "SCPTOOLS"."BANCO";


