spool gather_app_stats.log;
set echo on feedback on timing on

EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME => 'FINPAC_CUSTOM',METHOD_OPT => 'for all columns size skewonly',ESTIMATE_PERCENT => 100,CASCADE => TRUE);
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME => 'SPB_BRIDGE',METHOD_OPT => 'for all columns size skewonly',ESTIMATE_PERCENT => 100,CASCADE => TRUE);
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME => 'PANDATA',METHOD_OPT => 'for all columns size skewonly',ESTIMATE_PERCENT => 100,CASCADE => TRUE);
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME => 'SDIMIO',METHOD_OPT => 'for all columns size skewonly',ESTIMATE_PERCENT => 100,CASCADE => TRUE);
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME => 'FINPAC',METHOD_OPT => 'for all columns size skewonly',ESTIMATE_PERCENT => 100,CASCADE => TRUE);
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(OWNNAME => 'SDBANCO',METHOD_OPT => 'for all columns size skewonly',ESTIMATE_PERCENT => 100,CASCADE => TRUE);

spool off